### PR TITLE
Add support for Symfony 6

### PR DESCRIPTION
**Pull request by vblinden**

### CODE REVIEW

**Comment by xvilo** [comment]
LGTM

**Comment by shivas** [comment]
I'll leave it for @dontub to merge, as he may need to create a new release

**Comment by vblinden** [comment]
@dontub any change you can arrange this in the coming week?

**Comment by dontub** [comment]
Thanks for the PR, @vblinden!

Currently the tests don't run with Sf 6. I just had a quick look: There's an issue with Symfony Bundle Test https://github.com/SymfonyTest/symfony-bundle-test/issues/65. Switching to the current state of the master branch would solve this, though it requires some changes. Do you have time to have a look at this?

**Comment by vblinden** [comment]
@dontub The latest commit fixes the tests.

**Comment by dontub** [comment]
Thanks @vblinden

**Comment by vblinden** [comment]
Thanks @dontub , could you create a new release?

**Comment by dontub** [comment]
Version 4.0.1 is just released.

**Pull request merged**
