### PR TITLE
Fix GitDescribeFormatter prerelease versions

### LINKED ISSUE #90: `GitDescribeFormatter` produces invalid version strings for commit hashes starting with 0 and containing only numbers
My version is called `2.13.0-dev.0350536` and the `Shivas\VersioningBundle\Provider\VersionProvider` throws a `RuntimeException` because `Version::fromString` throws an `InvalidVersionString` exception.

Origin of the exception: `vendor/shivas/versioning-bundle/src/Service/VersionManager.php:114`

`0350536` are the first digits of the commit-hash this version originates from.

I know about the [regex](https://github.com/shivas/versioning-bundle/issues/67), see my tests here: https://regex101.com/r/UW2tok/2 but I don't understand what's going on.
It's like the hash-prefix is not "hexy" enough.

- Library Version: 4.0.0
- PHP Version: 7.4.30

### PR DESCRIPTION
**Pull request by nitwhiz**
closes #90

### CODE REVIEW

**Comment by nitwhiz** [comment]
ping?

**Comment by dontub** [comment]
Sorry for the delay, and thanks for the reminder :-) In #90 you suggested to add the commit hash as build metadata (separated by `+`). I agree that it would be the better choice. Any reason for not doing it like that?

**Comment by nitwhiz** [comment]
I wanted to keep the changes as non-invasive as possible. Also, this is closer to what git describe outputs itself.

I think if you want a specific format like this, library users should write a custom provider for that :)

**Comment by dontub** [comment]
All right. Thanks for the PR!

**Comment by nitwhiz** [comment]
Are there already plans on releasing a new patch version? I'd like to use this fix in a project at work, as this problem slightly impacts the stability of our staging environment.

**Comment by dontub** [comment]
Since there was no reason for not publishing a new release I just tagged version 4.0.3.

**Pull request merged**
